/**
 * 创意风格简历模板
 */

import type { ResumeTemplate, ResumeElement } from '@resume-editor/shared'

/**
 * 创意简历模板 - 彩色侧边栏
 */
export const creativeColorfulTemplate: ResumeTemplate = {
  id: 'creative-1',
  name: '彩色创意',
  description: '大胆配色，适合创意行业求职',
  category: 'creative',
  canvasSize: { width: 800, height: 1000 },
  createdAt: Date.now(),
  updatedAt: Date.now(),
  elements: [
    // 顶部彩色背景
    {
      id: 'header-bg',
      type: 'rect',
      x: 0,
      y: 0,
      width: 800,
      height: 180,
      fill: '#6c5ce7',
    },
    // 姓名标题
    {
      id: 'name-title',
      type: 'heading',
      x: 50,
      y: 50,
      width: 700,
      height: 60,
      content: '孙七',
      fontSize: 42,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#ffffff',
      textAlign: 'left',
    },
    // 职位
    {
      id: 'position',
      type: 'text',
      x: 50,
      y: 110,
      width: 700,
      height: 30,
      content: '创意总监 | 品牌设计师',
      fontSize: 18,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#dfe6e9',
      textAlign: 'left',
    },
    // 联系信息
    {
      id: 'contact-info',
      type: 'text',
      x: 50,
      y: 145,
      width: 700,
      height: 25,
      content: 'sunqi@design.com | +86 136-0000-0000 | 广州市',
      fontSize: 13,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#a29bfe',
      textAlign: 'left',
    },
    // 个人简介标题
    {
      id: 'summary-title',
      type: 'heading',
      x: 50,
      y: 210,
      width: 700,
      height: 30,
      content: '关于我',
      fontSize: 20,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#6c5ce7',
      textAlign: 'left',
    },
    // 个人简介内容
    {
      id: 'summary-content',
      type: 'text',
      x: 50,
      y: 250,
      width: 700,
      height: 80,
      content: '热爱创意设计，拥有8年品牌设计经验。擅长将品牌理念转化为视觉语言，为多家知名企业打造过成功的品牌形象。追求设计的极致与创新的突破。',
      fontSize: 14,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#2d3436',
      textAlign: 'left',
      lineHeight: 1.7,
    },
    // 工作经历标题
    {
      id: 'work-title',
      type: 'heading',
      x: 50,
      y: 360,
      width: 700,
      height: 30,
      content: '工作经历',
      fontSize: 20,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#6c5ce7',
      textAlign: 'left',
    },
    // 工作经历内容
    {
      id: 'work-content',
      type: 'text',
      x: 50,
      y: 400,
      width: 700,
      height: 180,
      content: `创意总监 | 蓝色光标 | 2020.03 - 至今
领导创意团队完成多个知名品牌的全案设计，年度服务客户超过20家。

高级设计师 | 奥美广告 | 2016.06 - 2020.02
参与多个4A项目，作品获得国内外设计奖项。`,
      fontSize: 14,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#2d3436',
      textAlign: 'left',
      lineHeight: 1.7,
    },
    // 技能标题
    {
      id: 'skills-title',
      type: 'heading',
      x: 50,
      y: 610,
      width: 700,
      height: 30,
      content: '专业技能',
      fontSize: 20,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#6c5ce7',
      textAlign: 'left',
    },
    // 技能内容
    {
      id: 'skills-content',
      type: 'text',
      x: 50,
      y: 650,
      width: 700,
      height: 100,
      content: '品牌策略 / 视觉设计 / UI设计 / 动态设计 / 团队管理 / 客户沟通\n熟练使用: Photoshop, Illustrator, After Effects, Figma, Sketch',
      fontSize: 14,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#2d3436',
      textAlign: 'left',
      lineHeight: 1.7,
    },
  ] as ResumeElement[],
  smartConfig: {
    stylePrompt: '大胆的紫色配色，顶部大面积彩色背景，适合创意行业，展现个性和创新精神',
    layoutHints: [
      { section: 'header', position: 'top', style: '大背景彩色头部' },
      { section: 'experience', position: 'left', style: '详细列表' },
      { section: 'skills', position: 'left', style: '分类展示' },
    ],
    colorScheme: {
      primary: '#6c5ce7',
      secondary: '#a29bfe',
      background: '#ffffff',
      text: '#2d3436',
      accent: '#dfe6e9',
    },
    typography: {
      headingFont: 'Arial',
      bodyFont: 'Arial',
      headingSizes: { min: 20, max: 42 },
      bodySizes: { min: 13, max: 18 },
    },
  },
}

/**
 * 创意简历模板2 - 渐变风格
 */
export const creativeGradientTemplate: ResumeTemplate = {
  id: 'creative-2',
  name: '渐变风格',
  description: '现代渐变配色，科技感十足',
  category: 'creative',
  canvasSize: { width: 800, height: 1000 },
  createdAt: Date.now(),
  updatedAt: Date.now(),
  elements: [
    // 左侧渐变背景（用矩形模拟）
    {
      id: 'sidebar-bg-1',
      type: 'rect',
      x: 0,
      y: 0,
      width: 280,
      height: 500,
      fill: '#0984e3',
    },
    {
      id: 'sidebar-bg-2',
      type: 'rect',
      x: 0,
      y: 500,
      width: 280,
      height: 500,
      fill: '#00b894',
    },
    // 头像占位
    {
      id: 'avatar-placeholder',
      type: 'ellipse',
      x: 90,
      y: 50,
      width: 100,
      height: 100,
      fill: '#74b9ff',
    },
    // 姓名标题
    {
      id: 'name-title',
      type: 'heading',
      x: 50,
      y: 170,
      width: 180,
      height: 40,
      content: '周八',
      fontSize: 28,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#ffffff',
      textAlign: 'center',
    },
    // 职位
    {
      id: 'position',
      type: 'text',
      x: 50,
      y: 215,
      width: 180,
      height: 25,
      content: '数据科学家',
      fontSize: 14,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#dfe6e9',
      textAlign: 'center',
    },
    // 左侧联系信息标题
    {
      id: 'contact-title',
      type: 'heading',
      x: 30,
      y: 280,
      width: 220,
      height: 25,
      content: '联系方式',
      fontSize: 14,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#ffffff',
      textAlign: 'left',
    },
    // 左侧联系信息
    {
      id: 'contact-info',
      type: 'text',
      x: 30,
      y: 310,
      width: 220,
      height: 100,
      content: `zhouba@email.com
+86 135-0000-0000
成都市高新区
github.com/zhouba`,
      fontSize: 12,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#dfe6e9',
      textAlign: 'left',
      lineHeight: 1.8,
    },
    // 左侧技能标题
    {
      id: 'skills-title',
      type: 'heading',
      x: 30,
      y: 430,
      width: 220,
      height: 25,
      content: '技术栈',
      fontSize: 14,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#ffffff',
      textAlign: 'left',
    },
    // 左侧技能
    {
      id: 'skills-content',
      type: 'text',
      x: 30,
      y: 460,
      width: 220,
      height: 100,
      content: `Python, R, SQL
TensorFlow, PyTorch
Spark, Hadoop
Tableau, Power BI`,
      fontSize: 12,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#dfe6e9',
      textAlign: 'left',
      lineHeight: 1.8,
    },
    // 右侧 - 个人简介标题
    {
      id: 'summary-title',
      type: 'heading',
      x: 310,
      y: 50,
      width: 440,
      height: 30,
      content: '个人简介',
      fontSize: 18,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#0984e3',
      textAlign: 'left',
    },
    // 右侧 - 个人简介内容
    {
      id: 'summary-content',
      type: 'text',
      x: 310,
      y: 85,
      width: 440,
      height: 80,
      content: '数据科学家，专注于机器学习和大数据分析。在多个行业领域有丰富的数据挖掘和建模经验，善于从数据中发现商业价值。',
      fontSize: 13,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#2d3436',
      textAlign: 'left',
      lineHeight: 1.7,
    },
    // 右侧 - 工作经历标题
    {
      id: 'work-title',
      type: 'heading',
      x: 310,
      y: 190,
      width: 440,
      height: 30,
      content: '工作经历',
      fontSize: 18,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#0984e3',
      textAlign: 'left',
    },
    // 右侧 - 工作经历内容
    {
      id: 'work-content',
      type: 'text',
      x: 310,
      y: 225,
      width: 440,
      height: 180,
      content: `高级数据科学家 | 字节跳动 | 2021.06 - 至今
负责推荐算法优化和用户行为分析，提升核心业务指标。

数据分析师 | 腾讯 | 2018.07 - 2021.05
参与社交产品数据分析，建立用户增长模型。`,
      fontSize: 13,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#2d3436',
      textAlign: 'left',
      lineHeight: 1.7,
    },
    // 右侧 - 教育背景标题
    {
      id: 'edu-title',
      type: 'heading',
      x: 310,
      y: 440,
      width: 440,
      height: 30,
      content: '教育背景',
      fontSize: 18,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      fill: '#00b894',
      textAlign: 'left',
    },
    // 右侧 - 教育背景内容
    {
      id: 'edu-content',
      type: 'text',
      x: 310,
      y: 475,
      width: 440,
      height: 80,
      content: `统计学 硕士 | 中国科学技术大学 | 2015.09 - 2018.06
数学 学士 | 四川大学 | 2011.09 - 2015.06`,
      fontSize: 13,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fill: '#2d3436',
      textAlign: 'left',
      lineHeight: 1.7,
    },
  ] as ResumeElement[],
  smartConfig: {
    stylePrompt: '现代渐变风格，左侧蓝绿渐变背景放置个人信息和技能，右侧放置详细经历，科技感强',
    layoutHints: [
      { section: 'header', position: 'left', style: '侧边栏头像+姓名' },
      { section: 'experience', position: 'right', style: '详细列表' },
      { section: 'education', position: 'right', style: '简洁列表' },
      { section: 'skills', position: 'left', style: '侧边栏列表' },
    ],
    colorScheme: {
      primary: '#0984e3',
      secondary: '#00b894',
      background: '#ffffff',
      text: '#2d3436',
      accent: '#74b9ff',
    },
    typography: {
      headingFont: 'Arial',
      bodyFont: 'Arial',
      headingSizes: { min: 14, max: 28 },
      bodySizes: { min: 12, max: 18 },
    },
  },
}
